Support shebang
purescript/purescript pull request #4214
Opened 2021-12-16 03:18 UTC by colinwahl

**Description of the change**

Supports optional shebang lines in modules. As part of parsing, shebang lines are chomped off the source & added to the parsed `Module`.

Intends to close #4210

---

**Checklist:**

- [ ] Added a file to CHANGELOG.d for this PR (see CHANGELOG.d/README.md)
~- [ ] Added myself to CONTRIBUTORS.md (if this is my first contribution)~
- [x] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [x] Added a test for the contribution (if applicable)

2021-12-16 18:46 UTC, JordanMartinez approved these changes
I'm wondering if we want to newtype the `[SourceToken]` argument to `lex` to further clarify that this can only be the shebang. Right now, it only serves to offset the initial `start` position before lexing begins, so one could pass in something else other than the `shebang` on accident.

2021-12-17 18:31 UTC, rhendric commented
Are shebangs part of PureScript modules? Or are they part of the on-disk representation of a module understood by `purs` the compiler? GHC takes the latter approach, for example; there's no mention of shebangs in the Haskell Language Report. But we could choose to say that the hypothetical PureScript language spec, which would already hypothetically allow a sequence of comments to precede a module definition, would now allow an initial sequence of those comments to be shebangs, a third comment type only usable at the start of a module parse.

I ask because this implementation feels to me like halfway between these two approaches. I think we should pick a side and, in one case, fully incorporate shebangs into the grammar; or, in the other case, not include shebangs in the module AST.

2021-12-17 19:50 UTC, JordanMartinez requested changes
Just an update. It was concluded that we should drop the need to add another token to the AST. Rather, the parser should parse lines of text starting with `#!` as a comment, but only when we know we're parsing a module. Since all comments are stored raw (e.g. `-- foo` gets parsed to `Comment "-- foo"`, not `Comment "foo"`), the shebang would be stored within the comments for the `module` keyword source token. This would require adding another `lex` variant that handles the shebang comment situation before calling `lex` with the rest of the text.

2021-12-17 19:56 UTC, natefaubion commented
>  It was concluded 

Just to be clear, by "it was concluded", this came up in a discussion at work, and I made a suggestion to lex it as a comment, essentially saying that shebangs are part of the module lexical grammar.

2022-05-27 07:03 UTC, JordanMartinez commented
This PR should be ready for review.

2022-05-28 14:28 UTC, JordanMartinez commented
Should the shebang comments be stored in the `ModuleHeader` separately from the non-shebang comments? Or should those be included? Right now, they are included.

2022-05-28 23:31 UTC, rhendric requested changes
I like this overall approach and the new tests are good. I'm a little dismayed by how verbose the implementation in the lexer is, but that's at least partly the pre-existing patterns that have been copied here instead of refactored. (Why do we go to the trouble of rolling our own monadic parser abstraction and then write out most of the lexer functions in longhand anyway? Perhaps there's a performance gotcha that isn't obvious to me?)

These suggestions are the most obvious opportunities for tidying up that I could see, but perhaps after this is merged I'll come back around and investigate a more combinatorial style for these top-level handlers.

2022-05-28 23:31 UTC, rhendric commented on src/Language/PureScript/CST/Lexer.hs
> +      pure Nothing
```suggestion
  shebangComment = isShebang >>= traverse lineComment
```

2022-05-28 23:31 UTC, rhendric commented on src/Language/PureScript/CST/Lexer.hs
> +    pure $ Comment (acc <> comm)
This is identical to the other `lineComment` in this file; please reuse.

2022-05-28 23:31 UTC, rhendric commented on src/Language/PureScript/CST/Lexer.hs
> +    | otherwise = Nothing
```suggestion
  unconsShebang = fmap ("#!", ) . Text.stripPrefix "#!"
```

2022-05-30 17:12 UTC, JordanMartinez commented
I've addressed the comments I got back from your review.

2022-05-30 19:32 UTC, rhendric approved these changes

2022-05-30 21:00 UTC, JordanMartinez approved these changes
I've overriding my previous review.

2022-05-30 21:05 UTC, merged