Bump depend purescript-installer to ^0.3.1
purescript/purescript pull request #4353
Opened 2022-06-11 00:47 UTC by imcotton

**Description of the change**

This bump is to address outdated NPM packages of the installer, see original issue at purescript/npm-installer#32 and its fixing PR purescript/npm-installer#33

---

**Checklist:**

- [ ] Added a file to CHANGELOG.d for this PR (see CHANGELOG.d/README.md)
- [ ] Added myself to CONTRIBUTORS.md (if this is my first contribution)
- [x] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

2022-06-11 02:19 UTC, JordanMartinez approved these changes

2022-06-11 02:20 UTC, JordanMartinez requested changes
Could you add yourself to the `CONTRIBUTORS.md` file?

And could you add a changelog entry in the `CHANGELOG.d` dir as an `internal` change?

2022-06-11 02:55 UTC, imcotton commented
Updated `CONTRIBUTORS.md` and put new entry to `CHANGELOG.d`, wasn't sure about these changes for an external version bump, thanks for the reminding.

2022-06-11 11:57 UTC, JordanMartinez approved these changes

2022-09-27 03:07 UTC, PureFunctor approved these changes

2022-09-27 03:12 UTC, merged