Fix space leak between modules during compilation
purescript/purescript pull request #4517
Opened 2023-11-07 19:17 UTC by MonoidMusician

To fix #4491.

For builds with a lot of warnings, memory usage grows drastically since it appears that the thunks for the warnings hang onto a lot of memory from compiling the module itself.

The goal of this change is to get memory usage for full builds back in line with partial builds.

This is just a WIP patch for now, showing a sort of minimal solution to the problem that isn't overly strict. I'd appreciate suggestions on how to accomplish it better.

`rnf x = rnf (show x)` is obviously a bad `NFData SimpleErrorMessage` instance, but it was going to be very tedious to derive `NFData` for every transitive data type. Perhaps it's better to make a dedicated function that computes just enough strictness for the errors? Or adding more strictness when computing the warnings in the first place, and to the data types themselves.

For part of our work codebase (which generates a lot of warnings), the difference is quite dramatic: 4GB of memory usage down to under 1GB, as measured by the GHC RTS profiling:

<img width="360" alt="image" src="https://github.com/purescript/purescript/assets/11701520/aae774de-4d13-4545-aa6d-0dd5fe369033">
<img width="360" alt="image" src="https://github.com/purescript/purescript/assets/11701520/f289ed5b-ef70-4139-bfe0-668e3e60dd06">

The difference is less dramatic, but still visible, when running on just our public dependencies – I suspect this is since they produce much fewer warnings.

I've been profiling with this command, though `-hc` is not a particularly helpful heap profile to track in retrospect:
```bash
$PURS +RTS -l-agu -i0.5 -hc -RTS compile -g corefn $(spago sources)
```

@mjrussell do you have a way to compile PureScript and test this out on your codebase?

**Checklist:**

- [ ] Added a file to CHANGELOG.d for this PR (see CHANGELOG.d/README.md)
- [x] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

2023-11-08 01:46 UTC, mjrussell commented
Wow! Nice work. I can try to give it a run this weekend. Sorry I never got you a smaller repro case like I promised

2023-11-10 20:49 UTC, mjrussell commented
@MonoidMusician I built your PR of purescript locally:
```
purs --version
0.15.12 [development build; commit: 27ec9cea1e45774647c58dfccc1665afc6d1d710 DIRTY]
```

I'm still seeing some pretty sizable memory pressure issues and longer compile times than on 15.2. I'm seeing about 26GB peak ram usage by this PR and 4m4s for a compilation of the bottleneck package whereas 15.2 maxes out at 1GB of ram and runs in 22 seconds.

2023-11-21 13:14 UTC, MonoidMusician commented
Thanks for taking the time to try it out!

I have pushed some more commits you can try: being more strict in the data kept between modules, and removing the CSE (in two commits: just dropping the CSE pass, and reverting the structural changes too).

On our codebase I actually don’t see a noticeable difference with these approaches. Just hoping it might help your codebase. If it doesn’t, we’ll have to look elsewhere!

2023-11-21 17:47 UTC, JordanMartinez commented
I feel like reverting the CSE pass doesn't give Ryan an opportunity to refactor that code. And I'd guess he hasn't because (besides potentially not having time) we still don't have a reproducible example.

2023-11-21 18:41 UTC, MonoidMusician commented
Yeah, I understand, this is just for debugging purposes to narrow down if it is CSE or not. (I don't necessarily believe it is CSE but that was one of the biggest changes that I can point to in the timeframe. Although I have another commit to look at now ...)

2023-11-23 02:35 UTC, mjrussell commented
@MonoidMusician I went to 7cba4ec and its close to 15.2 performance!

`spago build  88.56s user 7.10s system 272% cpu 35.124 total` so thats like ~3-4x worse time, but not 10-11x.

The memory pressure is greatly reduced, only about 2GB of ram, way under 26GB earlier in the PR.

I'll give the commits with just strictness a try

2023-11-23 02:46 UTC, mjrussell commented
[dec9091](https://github.com/purescript/purescript/pull/4517/commits/dec9091f7c6bea2f1bce45d690450832af31cf44) alone doesn't seem to fix the issue, in fact..it might be worse than [27ec9ce](https://github.com/purescript/purescript/pull/4517/commits/27ec9cea1e45774647c58dfccc1665afc6d1d710). 

`spago build  254.14s user 160.48s system 136% cpu 5:04.05 total`

The memory pressure was really strong, like 40GB of ram. On to the next

2023-11-23 02:55 UTC, mjrussell commented
Yeah looks to be CSE: On [33582d7](https://github.com/purescript/purescript/pull/4517/commits/33582d7b0874f2aa5426e71f0d58202a58a27883)

`spago build  87.00s user 7.48s system 246% cpu 38.336 total` 1-2 GB of ram

2023-11-23 03:07 UTC, rhendric commented
Again, if you can carve out something that you can make public and demonstrates the issue—it doesn't *have* to be minimal—there are at least a half dozen different things I can imagine that *might* improve memory use in the CSE pass and I would be happy to investigate if any of them actually help.

2023-11-23 03:55 UTC, mjrussell commented
I was writing up some explanation for why I can't make the file public b/c its internal types and we should try scripting out the generation of a 14k line file, while at the same time testing a fix that seems to alleviate the problem. 

`spago build  124.99s user 12.42s system 206% cpu 1:06.55 total` It has a bit higher mem pressure ~2GB constant but its easily workable.

Replacing `Data.Map` with `Data.Map.Strict` in `CSE.hs` does the trick.

I was expecting it to be something like that, building up thunks in a lazy structure. I thought you mind need to use RWS.Strict too but this is enough for a dramatic improvement

2023-11-23 04:19 UTC, MonoidMusician commented
interesting! it looks like we're chasing down rather separate issues then

I also have a fix coming up for more inter-module leaks WRT concurrency, so that should improve it even more

(also will help narrow down what modules are problematic)

2023-11-24 00:00 UTC, mjrussell commented
I pulled out that single Map change into https://github.com/purescript/purescript/pull/4521, thanks again!

2023-11-25 02:30 UTC, MonoidMusician commented
Okay, here's the second fix I promised:

With `+RTS -N1 -RTS`, the Haskell runtime was single threaded but the module builds were getting interleaved in some way, so the memory usage kind of bled across modules and peaked at 4.6GB. After introducing a semaphore to limit the concurrent module builds to the number of runtime threads, the memory usage looks more reasonable (a nice sawtooth graph) and peaked at 1.9GB.

<img width="360" alt="image" src="https://github.com/purescript/purescript/assets/11701520/39ffafa3-92a5-4701-8ddc-b6d5a87d502f">
<img width="360" alt="image" src="https://github.com/purescript/purescript/assets/11701520/70de0c08-ea58-4f17-b8b9-8f6a0abc044e">

I verified with the event logging that there are no longer too many modules being built simultaneously. (See trace.js if you want to replicate this.)

It matters less for builds with `-N8` (the default on my system) but still seems to make a difference.

I don't see significant differences with the CSE fix/reverts on this build, even measuring memory per-module in single threaded mode, so I guess it is orthogonal.

2023-11-25 13:37 UTC, MonoidMusician commented
More stats from the eventlogs:

with -N8 it can stay at 8 concurrent modules for 60% of the build and averages just under 6 concurrent modules ... but the user time speedup is only 2x-3x compared to a single-threaded build?

with -N6 it will stay at 6 concurrent modules for 70% of the build and average just under 5 concurrent modules, with comparable user time and a bit lower memory usage

with -N4 it gets a little slower (maybe 10%?) but still less memory usage

I can replicate these proportions without profiling, so there's probably more to investigate performance wise, but I'm happy with this for now.

2023-11-28 14:28 UTC, MonoidMusician commented
I timed each run and didn't see noticeable slow downs from the fixes here. Just speedups from the reduced memory usage, where applicable.

2023-11-29 20:06 UTC, JordanMartinez commented
@MonoidMusician Is this PR ready for review? Or are you still working on it? It's still in a draft state, so I'm unsure whether to wait or to start reviewing.

2023-12-02 04:00 UTC, MonoidMusician commented
Yeah, I'll un-draft it

2023-12-03 15:40 UTC, MonoidMusician commented on src/Language/PureScript/AST/Declarations.hs
> +
Haskell didn't know whether to choose newtype deriving or the default Generic instance. Same for the second one.

2023-12-11 17:15 UTC, JordanMartinez commented
Here's the steps I took. I don't know what I'm doing so feel free to correct me when I'm wrong. Since there's not a public codebase to compile this PR against, I went with the package set.
```sh
# Enter purescript root directory
$ pushd purescript
# Make a profile build
$ stack build --profile

# Install entire package set in another dir called 'z'
$ mkdir z
$ pushd z
$ spago init
$ spago install $(spago sources | cut -f 1 -d ' ' | tr '\n' ' ')
$ popd
# Setup eventlog2html in separate directory because PS's stack config 
# doesn't work on eventlog2html's latest version
$ popd
$ mkdir eventlog2html-temp-build
$ pushd eventlog2html-temp-build
$ stack build --copy-compiler-tool eventlog2html
$ popd

# Run the compiler on the package set
$ pushd purescript/z
# ... except that the below command fails...
$ stack --profile exec bash <<EOF
purs +RTS -l-agu -i1.5 -hc -RTS compile -g corefn $(spago sources)
EOF
# ... something about `purs` needing to be built with `-profile`.
# After more researching later, I passed the globs directly by producing the string manually
$ stack --profile exec -- purs +RTS -l-agu -i1.5 -hc -RTS compile -g corefn "src/**/*.purs" "test/**/*.purs" ".spago/prelude/v6.0.1/src/**/*.purs" # and so forth...

# Produce the HTML file
$ path/to/install/eventlog2html purs.eventlog
# Produce the JSON file
$ path/to/install/eventlog2html --json purs.eventlog
$ node ../debug/eventlog.js purs.eventlog.json > eventlog-output.txt
```

Outputs I get are:
- Screenshots of the HTML file's charts:
    - ![area-chart-profiled](https://github.com/purescript/purescript/assets/8413037/4eb7c6b4-17b8-4970-8dac-409e15dfa321)
    - ![other-chart-profiled](https://github.com/purescript/purescript/assets/8413037/b9572c15-b553-4d6c-a1b4-5308491ba375)
- [eventlog-output.txt](https://github.com/purescript/purescript/files/13638798/eventlog-output.txt)

2023-12-11 20:21 UTC, JordanMartinez approved these changes

2023-12-11 23:28 UTC, rhendric requested changes
It's unfortunate how deep into declarations/expressions the NFData instances need to go, but I also don't see a straightforward alternative that achieves the goal, and I agree with the general direction. After some cleanup, I'm good with this.

2023-12-11 23:28 UTC, rhendric commented on src/Language/PureScript/Make.hs
> +  -- Limit concurrent module builds to the number of capabilities as set by
```suggestion
  -- Limit concurrent module builds to the number of capabilities as
```

2023-12-11 23:28 UTC, rhendric commented on src/Language/PureScript/AST/Binders.hs
> +instance NFData Binder
Here and generally: can you consistently produce `NFData` instances using `deriving`, using `DeriveAnyClass` and [`DerivingStrategies`](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/deriving_strategies.html) (already in our default extensions list) as needed to enable/disambiguate this?

2023-12-11 23:28 UTC, rhendric commented on src/Language/PureScript/Sugar/Names/Env.hs
> +import Control.DeepSeq (NFData)
Are any of these instances in this module needed?

2023-12-15 16:39 UTC, JordanMartinez commented on src/Language/PureScript/CST/Layout.hs
> +instance NFData LayoutDelim
@MonoidMusician Mind if I push this fix, so that we can get this PR merged?

2023-12-18 17:25 UTC, MonoidMusician commented
Thanks for the reviews! Should be good now

@rhendric Agreed on all the places NFData needs to reach. But I'd rather be sure that the problem isn't going to come back, and I don't think there's noticeable performance impact from it. Thanks for the style tips.

@JordanMartinez I added those stack profiling instructions to eventlog.js too, thanks for that. I think the reason that `stack --profile exec bash` doesn't work (at least for me) is that my user directories take precedence over the stack provided $PATH.

Also a singular glob `.spago/*/*/src/**/*.purs` should work to pick up all spago packages (as long as there is only one version of each package downloaded).

2023-12-19 01:50 UTC, JordanMartinez commented on src/Language/PureScript/CST/Layout.hs
> +
Nitpick, I know, but can we get rid of this extra whitespace? The line above/below the language pragma?

2023-12-19 20:43 UTC, rhendric approved these changes

2023-12-20 02:04 UTC, merged